language: python
sudo: required
os:
  - linux
services:
  - docker

install:
  - pip install -r requirements.txt
script: pytest tests

before_deploy:
  - docker login registry.gitlab.com -u $DOCKER_USER  -p $DOCKER_PASS
  - docker pull registry.gitlab.com/atomatic/dpr-deploy
deploy:
  skip_cleanup: true
  provider: script
  script: ./build.sh
  on:
    repo: subhankarb/travis_trial
    branch: master
