language: python
sudo: required
os:
  - linux
services:
  - docker

install:
  - pip install -r requirements.txt
script: pytest tests

before_deploy:
  - docker login -u="$DOCKER_USER"  -p="$DOCKER_PASS" registry.gitlab.com
  - docker pull registry.gitlab.com/atomatic/dpr-deploy
deploy:
  skip_cleanup: true
  provider: script
  script: docker run -it registry.gitlab.com/atomatic/dpr-deploy --extra-vars "@external_config.json" --tags "zappa"
  on:
    repo: subhankarb/travis_trial
    branch: master
